#ifndef THIRD_PARTY_NEWLIB_SRC_NEWLIB_LIBC_SYS_ENCLAVE_INCLUDE_LINUX_RANDOM_H_
#define THIRD_PARTY_NEWLIB_SRC_NEWLIB_LIBC_SYS_ENCLAVE_INCLUDE_LINUX_RANDOM_H_

#include <sys/ioccom.h>

#define RNDGETENTCNT _IOR( 'R', 0x00, int )

#endif  // THIRD_PARTY_NEWLIB_SRC_NEWLIB_LIBC_SYS_ENCLAVE_INCLUDE_LINUX_RANDOM_H_
